### ISSUE TITLE
Generating sha512 password

### ISSUE THREAD

**Issue by Zelaf** [RyanSquared/blag#2]
Generating a sha512 password should be added to instructions.

`echo -n 'password' | sha512sum`

Output:
`b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86  -`

Remove the `-`

And then you have the password.

**Comment by RyanSquared** [comment]
Or just `echo -n 'password' | sha512sum | awk '{ print $1 }'`

**Comment by RyanSquared** [comment]
fixed by adding `passwd.sh`.
